apiVersion: v1 
kind: Pod 
metadata:
  name: my-pod
spec:
  containers: 
    - name: my-container
      image: busybox
      command: ["sh","-c","sleep 3600"]
      envFrom: # to integrate multiple maps
        - configMapRef:
            name: my-configmap
        - secretRef:
            name: my-secret