apiVersion: v1 
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # DB_PASSWORD: YXJ1bmt1bWFyc2VjcmV0 <- base64 encription created by a command in gitbash
  DB_PASSWORD: YXJ1bmt1bWFyc2VjcmV0