apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    department: development
spec:
  containers:
    - name: myapp-container
      image: kicbase/echo-server:1.0
      ports:
        - containerPort: 8080