apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
  namespace: my-namespace
spec: 
  containers:
    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        memory: "128Mi"  #Mebibyte
        cpu: "100m" #cpu 10%
      limits:
        memory: "256Mi"
        cpu: "200m"