apiVersion: v1
kind: Service
metadata:
  name: welcome-service
spec:
  type: NodePort
  selector:
    app: welcome # same as lebal port in pods
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080